/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectRouteImport } from './routes/subject'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MockExamRouteImport } from './routes/mock-exam'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as ParentScheduleRouteImport } from './routes/parent.schedule'
import { Route as ParentProgressRouteImport } from './routes/parent.progress'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as ParentAccountRouteImport } from './routes/parent.account'
import { Route as MockExamTakeRouteImport } from './routes/mock-exam.take'

const SubjectRoute = SubjectRouteImport.update({
  id: '/subject',
  path: '/subject',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MockExamRoute = MockExamRouteImport.update({
  id: '/mock-exam',
  path: '/mock-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentScheduleRoute = ParentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAccountRoute = ParentAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ParentRoute,
} as any)
const MockExamTakeRoute = MockExamTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => MockExamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/meeting': typeof MeetingRoute
  '/mock-exam': typeof MockExamRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subject': typeof SubjectRoute
  '/mock-exam/take': typeof MockExamTakeRoute
  '/parent/account': typeof ParentAccountRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/meeting': typeof MeetingRoute
  '/mock-exam': typeof MockExamRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subject': typeof SubjectRoute
  '/mock-exam/take': typeof MockExamTakeRoute
  '/parent/account': typeof ParentAccountRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/meeting': typeof MeetingRoute
  '/mock-exam': typeof MockExamRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subject': typeof SubjectRoute
  '/mock-exam/take': typeof MockExamTakeRoute
  '/parent/account': typeof ParentAccountRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/schedule': typeof ParentScheduleRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/chat'
    | '/library'
    | '/live'
    | '/meeting'
    | '/mock-exam'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/sitemap.xml'
    | '/subject'
    | '/mock-exam/take'
    | '/parent/account'
    | '/parent/messages'
    | '/parent/progress'
    | '/parent/schedule'
    | '/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/chat'
    | '/library'
    | '/live'
    | '/meeting'
    | '/mock-exam'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/sitemap.xml'
    | '/subject'
    | '/mock-exam/take'
    | '/parent/account'
    | '/parent/messages'
    | '/parent/progress'
    | '/parent/schedule'
    | '/video/$id'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/chat'
    | '/library'
    | '/live'
    | '/meeting'
    | '/mock-exam'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/sitemap.xml'
    | '/subject'
    | '/mock-exam/take'
    | '/parent/account'
    | '/parent/messages'
    | '/parent/progress'
    | '/parent/schedule'
    | '/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  ChatRoute: typeof ChatRoute
  LibraryRoute: typeof LibraryRoute
  LiveRoute: typeof LiveRoute
  MeetingRoute: typeof MeetingRoute
  MockExamRoute: typeof MockExamRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubjectRoute: typeof SubjectRoute
  VideoIdRoute: typeof VideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subject': {
      id: '/subject'
      path: '/subject'
      fullPath: '/subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-exam': {
      id: '/mock-exam'
      path: '/mock-exam'
      fullPath: '/mock-exam'
      preLoaderRoute: typeof MockExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/schedule': {
      id: '/parent/schedule'
      path: '/schedule'
      fullPath: '/parent/schedule'
      preLoaderRoute: typeof ParentScheduleRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/account': {
      id: '/parent/account'
      path: '/account'
      fullPath: '/parent/account'
      preLoaderRoute: typeof ParentAccountRouteImport
      parentRoute: typeof ParentRoute
    }
    '/mock-exam/take': {
      id: '/mock-exam/take'
      path: '/take'
      fullPath: '/mock-exam/take'
      preLoaderRoute: typeof MockExamTakeRouteImport
      parentRoute: typeof MockExamRoute
    }
  }
}

interface MockExamRouteChildren {
  MockExamTakeRoute: typeof MockExamTakeRoute
}

const MockExamRouteChildren: MockExamRouteChildren = {
  MockExamTakeRoute: MockExamTakeRoute,
}

const MockExamRouteWithChildren = MockExamRoute._addFileChildren(
  MockExamRouteChildren,
)

interface ParentRouteChildren {
  ParentAccountRoute: typeof ParentAccountRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentProgressRoute: typeof ParentProgressRoute
  ParentScheduleRoute: typeof ParentScheduleRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAccountRoute: ParentAccountRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentProgressRoute: ParentProgressRoute,
  ParentScheduleRoute: ParentScheduleRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  ChatRoute: ChatRoute,
  LibraryRoute: LibraryRoute,
  LiveRoute: LiveRoute,
  MeetingRoute: MeetingRoute,
  MockExamRoute: MockExamRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubjectRoute: SubjectRoute,
  VideoIdRoute: VideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
